### ISSUE TITLE
Any way to add plain text on the QR code?

### ISSUE THREAD

**Issue by llioor** [SimpleSoftwareIO/simple-qrcode#24]
Something like a number or a text on the bottom of the QR.
I saw some classes who use setLabel('text here') to the QR code generator..
Do we have it here as well?
Thanks.

**Comment by SimplyThomas** [comment]
This isn't something that we're likely to support because this is really a styling request and it's out of the scope of this project. I recommend that you use basic HTML/CSS styling to achieve what you're talking about. A quick example to achieve what you're looking for:
 
HTML:
````html
<div class="qrcode-wrapper">
  <div class="qrcode">
    <--! Insert your QrCode here -->
  </div>
  <div class="qrcode-label">
    Label Text Goes Here
  </div>
</div>
````
CSS:
````CSS
.qrcode-wrapper {
  position: relative; 
  /* Have to have a wrapper with relative positioning.
     This keeps the label position absolute to the QrCode
     and not positioned absolute to the whole DOM */
}
.qrcode {
/* QrCode styling */
}
.qrcode-label {
  position: absolute; /* Positions absolute to the wrapper */
  bottom: 1em; /* You are encouraged to change these values to get the label where you want it */
  right: 1em;
}
````

Let me know if you have any issues implementing what you're looking for with HTML/CSS and I'll see what I can come up with. Hopefully this example is more then enough to get you going. :)

-Tom
